/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ispd.gui;

import ispd.gui.iconico.Aresta;
import ispd.gui.iconico.grade.DesenhoGrade;
import ispd.gui.iconico.grade.Link;
import ispd.gui.iconico.grade.Machine;
import ispd.motor.falha.Falha;
import ispd.motor.falha.FalhaExponencial;
import ispd.motor.falha.FalhaPorNo;
import ispd.motor.filas.servidores.implementacao.Vertice;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public class EscolherFalhas extends javax.swing.JFrame {
    
    private Falha falhaprocessamento;
    private Falha falhacomunicacao;
    private HashMap<String, int[]> maquinasfalhadas;
    DesenhoGrade aDesenho;
    /**
     * Creates new form EscolherFalhas
     */
    public EscolherFalhas() {
        maquinasfalhadas = new HashMap<String, int[]>();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.falhaprocessamento = new FalhaExponencial(0,0,0);
        this.falhacomunicacao = new FalhaExponencial(0,0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        random = new javax.swing.JTabbedPane();
        jPanelModo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lifetimespinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        lengthspinner = new javax.swing.JSpinner();
        nodesspinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelModo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lifetimespinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        lengthspinner1 = new javax.swing.JSpinner();
        nodesspinner1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pernode = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        failTable = new javax.swing.JTable();
        inceptionSpinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        recoverySpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        randomRadio = new javax.swing.JRadioButton();
        pernodeRadio = new javax.swing.JRadioButton();
        central = new javax.swing.JScrollPane();

        random.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelModo.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanelModo.setMinimumSize(new java.awt.Dimension(500, 60));

        jLabel6.setText("Number of nodes");

        jLabel5.setText("Downtime");

        jLabel1.setText("Lifetime");

        jLabel2.setText("machines");

        jLabel7.setText("seconds");

        jLabel8.setText("seconds");

        javax.swing.GroupLayout jPanelModoLayout = new javax.swing.GroupLayout(jPanelModo);
        jPanelModo.setLayout(jPanelModoLayout);
        jPanelModoLayout.setHorizontalGroup(
            jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nodesspinner, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(lengthspinner)
                    .addComponent(lifetimespinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModoLayout.setVerticalGroup(
            jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(nodesspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(lifetimespinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(lengthspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        random.addTab("Processing nodes", jPanelModo);
        jPanelModo.getAccessibleContext().setAccessibleName("");

        jPanelModo1.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanelModo1.setMinimumSize(new java.awt.Dimension(500, 60));

        jLabel9.setText("Number of links");

        jLabel10.setText("Downtime");

        jLabel3.setText("Lifetime");

        jLabel4.setText("links");

        jLabel11.setText("seconds");

        jLabel12.setText("seconds");

        javax.swing.GroupLayout jPanelModo1Layout = new javax.swing.GroupLayout(jPanelModo1);
        jPanelModo1.setLayout(jPanelModo1Layout);
        jPanelModo1Layout.setHorizontalGroup(
            jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nodesspinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(lengthspinner1)
                    .addComponent(lifetimespinner1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModo1Layout.setVerticalGroup(
            jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(nodesspinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3)
                    .addComponent(lifetimespinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(lengthspinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        random.addTab("Communication Nodes", jPanelModo1);

        failTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resource", "Inception", "Recovery"
            }
        ));
        jScrollPane1.setViewportView(failTable);

        jLabel13.setText("Inception");

        jLabel14.setText("Recovery");

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Seconds");

        jLabel16.setText("Seconds");

        jButton3.setText("Clear All");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pernodeLayout = new javax.swing.GroupLayout(pernode);
        pernode.setLayout(pernodeLayout);
        pernodeLayout.setHorizontalGroup(
            pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pernodeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inceptionSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(recoverySpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(33, 33, 33)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pernodeLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pernodeLayout.setVerticalGroup(
            pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pernodeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inceptionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton1)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pernodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(recoverySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel16)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setTitle("Failure");
        setType(java.awt.Window.Type.POPUP);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Failure distribution"));

        randomRadio.setText("Generic");
        randomRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomRadioActionPerformed(evt);
            }
        });

        pernodeRadio.setText("By node");
        pernodeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pernodeRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(randomRadio)
                .addGap(125, 125, 125)
                .addComponent(pernodeRadio)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomRadio)
                    .addComponent(pernodeRadio))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(central)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(central, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void update(DesenhoGrade aDesenho){
        this.aDesenho = aDesenho;
        Machine procs[] = new Machine[aDesenho.getVertices().size()];
        Link links[] = new Link[aDesenho.getArestas().size()];
       
        for(int i = 0; i < procs.length; i++){
            procs[i] = (Machine) aDesenho.getVertices().toArray()[i];
        }
       
        for(int i = 0; i < links.length; i++){
            links[i] = (Link) aDesenho.getArestas().toArray()[i];
        }
       
        DefaultTableModel model = (DefaultTableModel) failTable.getModel();
       
        while(failTable.getRowCount() > 0)
            model.removeRow(0);
       
        for(int i = 0 ; i < procs.length; i++){
            int t[] = maquinasfalhadas.get(procs[i].getId());
            Object[] linha = new Object[3];
            linha[0] = procs[i].getId().getNome();
            if(t == null){
               linha[1] = " - ";
               linha[2] = " - ";
            }else{
               linha[1] = t[0];
               linha[2] = t[1];
            }
            model.addRow(linha);
        }
        
        for(int i = 0 ; i < links.length; i++){
            int t[] = maquinasfalhadas.get(links[i].getId());
            Object[] linha = new Object[3];
            linha[0] = links[i].getId().getNome();
            if(t == null){
               linha[1] = " - ";
               linha[2] = " - ";
            }else{
               linha[1] = t[0];
               linha[2] = t[1];
            }
            model.addRow(linha);
        }
        
    }
    
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        if(randomRadio.isSelected())
            gerarAleatorio();
        
        if(pernodeRadio.isSelected())
            gerarPorNo();
        
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void gerarPorNo(){
        falhaprocessamento = new FalhaPorNo(maquinasfalhadas);
        falhacomunicacao = falhaprocessamento;
    }
    
    private void gerarAleatorio(){
        int p = (Integer)lifetimespinner.getValue();
        double life = (double)p;
        p = (Integer)lengthspinner.getValue();
        double length = (double)p;
        p = (Integer)nodesspinner.getValue();
        int n = p;
        falhaprocessamento = new FalhaExponencial(life, length, n);
        
        p = (Integer)lifetimespinner1.getValue();
        life = (double)p;
        p = (Integer)lengthspinner1.getValue();
        length = (double)p;
        p = (Integer)nodesspinner1.getValue();
        n = p;
        falhacomunicacao = new FalhaExponencial(life, length, n);
        
        setVisible(false);
    }
    
    private void randomRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomRadioActionPerformed
        setRandom();
        
    }//GEN-LAST:event_randomRadioActionPerformed

    private void pernodeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pernodeRadioActionPerformed
        setPerNode();
    }//GEN-LAST:event_pernodeRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rows[] = failTable.getSelectedRows();
        DefaultTableModel model = (DefaultTableModel) failTable.getModel();
        Integer inception = (Integer) inceptionSpinner.getValue();
        Integer recovery = (Integer) recoverySpinner.getValue();
        int[] t = new int[2];
        t[0] = inception;
        t[1] = recovery;
        
        for(int i = 0; i < rows.length; i++){
            String id = (String) model.getValueAt(rows[i], 0);
            model.setValueAt(inception, rows[i], 1);
            model.setValueAt(recovery, rows[i], 2);
            maquinasfalhadas.put(id, t);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rows[] = failTable.getSelectedRows();
        DefaultTableModel model = (DefaultTableModel) failTable.getModel();
        
        for(int i = 0; i < rows.length; i++){
            String id = (String) model.getValueAt(rows[i], 0);
            model.setValueAt(" - ", rows[i], 1);
            model.setValueAt(" - ", rows[i], 2);
            maquinasfalhadas.remove(id);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        maquinasfalhadas.clear();
        update(aDesenho);
    }//GEN-LAST:event_jButton3ActionPerformed
   
    private void setPerNode(){
        randomRadio.setSelected(false);
        central.setViewportView(pernode);
    }
    
    private void setRandom(){
        pernodeRadio.setSelected(false);
        central.setViewportView(random);
        
    }
    
    public Falha getFalhaProcessamento() {
        return falhaprocessamento;
    }

    public Falha getFalhacomunicacao() {
        return falhacomunicacao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane central;
    private javax.swing.JTable failTable;
    private javax.swing.JSpinner inceptionSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelModo;
    private javax.swing.JPanel jPanelModo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner lengthspinner;
    private javax.swing.JSpinner lengthspinner1;
    private javax.swing.JSpinner lifetimespinner;
    private javax.swing.JSpinner lifetimespinner1;
    private javax.swing.JSpinner nodesspinner;
    private javax.swing.JSpinner nodesspinner1;
    private javax.swing.JPanel pernode;
    private javax.swing.JRadioButton pernodeRadio;
    private javax.swing.JTabbedPane random;
    private javax.swing.JRadioButton randomRadio;
    private javax.swing.JSpinner recoverySpinner;
    // End of variables declaration//GEN-END:variables
}
