/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GerarEscalonador.java
 *
 * Created on 30/04/2011, 12:18:41
 */
package ispd.janela;

import ispd.ValidaValores;
import java.awt.Toolkit;

/**
 *
 * @author denison_usuario
 */
public class GerarEscalonador extends javax.swing.JDialog {

    private int passoAtual;
    private String caminho;
    private String ordenacao;
    private String formula;

    /** Creates new form GerarEscalonador */
    public GerarEscalonador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.caminho = "C:\\lol\\";
        this.passoAtual = 1;
        this.ordenacao = "Random";
        this.formula = "";
        initComponents();
        this.jScrollPanePrincipal.setViewportView(this.jPanelPasso1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPasso1 = new javax.swing.JPanel();
        jLabelNomeEsc = new javax.swing.JLabel();
        jTextFieldP1NomeEsc = new javax.swing.JTextField();
        jLabelLocalArq = new javax.swing.JLabel();
        jTextFieldLocalArq = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelP1Informacao = new javax.swing.JLabel();
        jPanelPasso2 = new javax.swing.JPanel();
        jLabelP1Informacao1 = new javax.swing.JLabel();
        jRadioButtonEstatica = new javax.swing.JRadioButton();
        jRadioButtonDinamica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonCentralizada = new javax.swing.JRadioButton();
        jRadioButtonDistribuida = new javax.swing.JRadioButton();
        jLabelP2Forma = new javax.swing.JLabel();
        jFormattedTextFieldP2Tempo = new javax.swing.JFormattedTextField();
        jRadioButtonP2Tempo = new javax.swing.JRadioButton();
        jRadioButtonP2Tarefa = new javax.swing.JRadioButton();
        jRadioButtonP2Misto = new javax.swing.JRadioButton();
        jFormattedTextFieldP2Misto = new javax.swing.JFormattedTextField();
        jPanelPasso3 = new javax.swing.JPanel();
        jLabelFormula = new javax.swing.JLabel();
        jTextFieldP3Formula = new javax.swing.JTextField();
        jLabelP1Informacao2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonP3Add = new javax.swing.JButton();
        jButtonP3Sub = new javax.swing.JButton();
        jButtonP3AbreParent = new javax.swing.JButton();
        jButtonP3FechaParent = new javax.swing.JButton();
        jButtonP3Div = new javax.swing.JButton();
        jButtonP3Mult = new javax.swing.JButton();
        jButtonP3Voltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonP3TComputacao = new javax.swing.JButton();
        jButtonP3TComunicacao = new javax.swing.JButton();
        jButtonP3NTSubmetidas = new javax.swing.JButton();
        jButtonP3NTAtendidas = new javax.swing.JButton();
        jButtonP3NTConcluidas = new javax.swing.JButton();
        jButtonP3PComputUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonP3Crescente = new javax.swing.JRadioButton();
        jRadioButtonP3Decrescente = new javax.swing.JRadioButton();
        jRadioButtonP3Random = new javax.swing.JRadioButton();
        jPanelPassos = new javax.swing.JPanel();
        jLabelPassos = new javax.swing.JLabel();
        jLabelPasso1 = new javax.swing.JLabel();
        jLabelPasso2 = new javax.swing.JLabel();
        jLabelPasso3 = new javax.swing.JLabel();
        jPanelControle = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPanePrincipal = new javax.swing.JScrollPane();

        jPanelPasso1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informar nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N

        jLabelNomeEsc.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelNomeEsc.setText("Nome do escalonador: ");

        jTextFieldP1NomeEsc.setText("NovoEscalonador");
        jTextFieldP1NomeEsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldP1NomeEscKeyReleased(evt);
            }
        });

        jLabelLocalArq.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelLocalArq.setText("Local do arquivo:");

        jTextFieldLocalArq.setEditable(false);
        jTextFieldLocalArq.setText("F:\\Projetos\\bibliotecas\\iSPD\\ispd\\externo\\escalonador\\NovoEscalonador.java");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabelP1Informacao.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanelPasso1Layout = new javax.swing.GroupLayout(jPanelPasso1);
        jPanelPasso1.setLayout(jPanelPasso1Layout);
        jPanelPasso1Layout.setHorizontalGroup(
            jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeEsc)
                    .addComponent(jLabelLocalArq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLocalArq, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jTextFieldP1NomeEsc, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(jPanelPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelP1Informacao, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPasso1Layout.setVerticalGroup(
            jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeEsc)
                    .addComponent(jTextFieldP1NomeEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPasso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalArq)
                    .addComponent(jTextFieldLocalArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelP1Informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanelPasso2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informar as características", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N

        jLabelP1Informacao1.setForeground(new java.awt.Color(204, 0, 0));

        jRadioButtonEstatica.setSelected(true);
        jRadioButtonEstatica.setText("Estática");
        jRadioButtonEstatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstaticaActionPerformed(evt);
            }
        });

        jRadioButtonDinamica.setText("Dinâmica");
        jRadioButtonDinamica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDinamicaActionPerformed(evt);
            }
        });

        jLabel1.setText("Busca de informações:");

        jLabel2.setText("Topologia:");

        jRadioButtonCentralizada.setSelected(true);
        jRadioButtonCentralizada.setText("Centralizada");
        jRadioButtonCentralizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCentralizadaActionPerformed(evt);
            }
        });

        jRadioButtonDistribuida.setText("Distribuida");
        jRadioButtonDistribuida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDistribuidaActionPerformed(evt);
            }
        });

        jLabelP2Forma.setText("Forma de atualização");
        jLabelP2Forma.setEnabled(false);

        jFormattedTextFieldP2Tempo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldP2Tempo.setText("1");
        jFormattedTextFieldP2Tempo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextFieldP2Tempo.setEnabled(false);

        jRadioButtonP2Tempo.setSelected(true);
        jRadioButtonP2Tempo.setText("Intervalo de tempo");
        jRadioButtonP2Tempo.setToolTipText("Variáveis dinâmicas serão atualizadas após a passagem do tempo especificada");
        jRadioButtonP2Tempo.setEnabled(false);
        jRadioButtonP2Tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP2TempoActionPerformed(evt);
            }
        });

        jRadioButtonP2Tarefa.setText("Chegada de tarefa");
        jRadioButtonP2Tarefa.setEnabled(false);
        jRadioButtonP2Tarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP2TarefaActionPerformed(evt);
            }
        });

        jRadioButtonP2Misto.setText("Misto");
        jRadioButtonP2Misto.setEnabled(false);
        jRadioButtonP2Misto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP2MistoActionPerformed(evt);
            }
        });

        jFormattedTextFieldP2Misto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldP2Misto.setText("1");
        jFormattedTextFieldP2Misto.setEnabled(false);

        javax.swing.GroupLayout jPanelPasso2Layout = new javax.swing.GroupLayout(jPanelPasso2);
        jPanelPasso2.setLayout(jPanelPasso2Layout);
        jPanelPasso2Layout.setHorizontalGroup(
            jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDinamica)
                            .addComponent(jRadioButtonEstatica)))
                    .addGroup(jPanelPasso2Layout.createSequentialGroup()
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPasso2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(84, 84, 84)
                                    .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonCentralizada)
                                        .addComponent(jLabel2)
                                        .addComponent(jRadioButtonDistribuida)))
                                .addGroup(jPanelPasso2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonP2Tarefa)
                                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPasso2Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonP2Misto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jFormattedTextFieldP2Misto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPasso2Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonP2Tempo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jFormattedTextFieldP2Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelP2Forma))
                        .addGap(123, 123, 123)
                        .addComponent(jLabelP1Informacao1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPasso2Layout.setVerticalGroup(
            jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso2Layout.createSequentialGroup()
                .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelP1Informacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPasso2Layout.createSequentialGroup()
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonEstatica)
                            .addComponent(jRadioButtonCentralizada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDinamica)
                            .addComponent(jRadioButtonDistribuida))
                        .addGap(11, 11, 11)
                        .addComponent(jLabelP2Forma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonP2Tempo)
                            .addComponent(jFormattedTextFieldP2Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonP2Tarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPasso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonP2Misto)
                            .addComponent(jFormattedTextFieldP2Misto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPasso3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordem de atendimento das tarefas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanelPasso3.setPreferredSize(new java.awt.Dimension(559, 244));

        jLabelFormula.setFont(new java.awt.Font("Comic Sans MS", 0, 11));
        jLabelFormula.setText("Fórmula:");

        jTextFieldP3Formula.setEditable(false);
        jTextFieldP3Formula.setFont(new java.awt.Font("Verdana", 1, 11));
        jTextFieldP3Formula.setText("Random( )");
        jTextFieldP3Formula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP3FormulaActionPerformed(evt);
            }
        });

        jLabelP1Informacao2.setForeground(new java.awt.Color(204, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operadores e precedencia"));

        jButtonP3Add.setText("+");
        jButtonP3Add.setMaximumSize(new java.awt.Dimension(37, 23));
        jButtonP3Add.setMinimumSize(new java.awt.Dimension(37, 23));
        jButtonP3Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3AddActionPerformed(evt);
            }
        });

        jButtonP3Sub.setText("-");

        jButtonP3AbreParent.setText("(");

        jButtonP3FechaParent.setText(")");

        jButtonP3Div.setText("/");

        jButtonP3Mult.setText("*");
        jButtonP3Mult.setMaximumSize(new java.awt.Dimension(37, 23));
        jButtonP3Mult.setMinimumSize(new java.awt.Dimension(37, 23));

        jButtonP3Voltar.setText("←");
        jButtonP3Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonP3AbreParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonP3Mult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonP3Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonP3Div, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButtonP3Sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonP3FechaParent, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonP3Voltar)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonP3Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonP3Sub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonP3Mult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonP3Div))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonP3AbreParent)
                            .addComponent(jButtonP3FechaParent)))
                    .addComponent(jButtonP3Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(4, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Variaveis"));

        jButtonP3TComputacao.setText("TCP");
        jButtonP3TComputacao.setToolTipText("Tamanho Computacional");
        jButtonP3TComputacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3TComputacaoActionPerformed(evt);
            }
        });

        jButtonP3TComunicacao.setText("TC");
        jButtonP3TComunicacao.setToolTipText("Tamanho da Comunicação");
        jButtonP3TComunicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3TComunicacaoActionPerformed(evt);
            }
        });

        jButtonP3NTSubmetidas.setText("NTS");
        jButtonP3NTSubmetidas.setToolTipText("Número de tarefas submetidas pelo usuário");
        jButtonP3NTSubmetidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3NTSubmetidasActionPerformed(evt);
            }
        });

        jButtonP3NTAtendidas.setText("NTA");
        jButtonP3NTAtendidas.setToolTipText("Número de tarefas atendidas do usuário");
        jButtonP3NTAtendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3NTAtendidasActionPerformed(evt);
            }
        });

        jButtonP3NTConcluidas.setText("NTC");
        jButtonP3NTConcluidas.setToolTipText("Número de tarefas concluídas do usuário");
        jButtonP3NTConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3NTConcluidasActionPerformed(evt);
            }
        });

        jButtonP3PComputUser.setText("PCU");
        jButtonP3PComputUser.setToolTipText("Poder computacional do usuário");
        jButtonP3PComputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP3PComputUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonP3NTConcluidas, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP3PComputUser, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonP3NTSubmetidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jButtonP3TComputacao, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonP3TComunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButtonP3NTAtendidas, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP3TComputacao)
                    .addComponent(jButtonP3TComunicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP3NTSubmetidas)
                    .addComponent(jButtonP3NTAtendidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP3NTConcluidas)
                    .addComponent(jButtonP3PComputUser))
                .addContainerGap(4, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenação"));

        jRadioButtonP3Crescente.setText("Crescente");
        jRadioButtonP3Crescente.setToolTipText("Escalona através da fórmula gerada de maneira crescente");
        jRadioButtonP3Crescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP3CrescenteActionPerformed(evt);
            }
        });

        jRadioButtonP3Decrescente.setText("Decrescente");
        jRadioButtonP3Decrescente.setToolTipText("Escalona através da fórmula gerada de maneira decrescente");
        jRadioButtonP3Decrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP3DecrescenteActionPerformed(evt);
            }
        });

        jRadioButtonP3Random.setSelected(true);
        jRadioButtonP3Random.setText("Random");
        jRadioButtonP3Random.setToolTipText("Escalona as tarefas de Maneira Randomica (Sorteio)");
        jRadioButtonP3Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonP3RandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonP3Crescente)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonP3Decrescente)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonP3Random)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonP3Crescente)
                .addGap(14, 14, 14)
                .addComponent(jRadioButtonP3Decrescente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jRadioButtonP3Random))
        );

        javax.swing.GroupLayout jPanelPasso3Layout = new javax.swing.GroupLayout(jPanelPasso3);
        jPanelPasso3.setLayout(jPanelPasso3Layout);
        jPanelPasso3Layout.setHorizontalGroup(
            jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso3Layout.createSequentialGroup()
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFormula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldP3Formula)))
                .addGap(64, 64, 64)
                .addComponent(jLabelP1Informacao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPasso3Layout.setVerticalGroup(
            jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPasso3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFormula)
                    .addComponent(jTextFieldP3Formula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabelP1Informacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPasso3Layout.createSequentialGroup()
                        .addGroup(jPanelPasso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Escalonador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("imagens/Logo_GSPD_128.png")));

        jPanelPassos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPassos.setBorder(new javax.swing.border.MatteBorder(null));

        jLabelPassos.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelPassos.setText("<html><b>Passos<br>----------------</b></html>");

        jLabelPasso1.setText("1 - Informar nome");

        jLabelPasso2.setText("2 - Caracteristicas");
        jLabelPasso2.setEnabled(false);

        jLabelPasso3.setText("3 - Escalonar Tarefas");
        jLabelPasso3.setEnabled(false);

        javax.swing.GroupLayout jPanelPassosLayout = new javax.swing.GroupLayout(jPanelPassos);
        jPanelPassos.setLayout(jPanelPassosLayout);
        jPanelPassosLayout.setHorizontalGroup(
            jPanelPassosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPassosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPassos, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jLabelPasso1)
                    .addComponent(jLabelPasso2)
                    .addComponent(jLabelPasso3))
                .addContainerGap())
        );
        jPanelPassosLayout.setVerticalGroup(
            jPanelPassosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPassos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPasso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasso3)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jButtonVoltar.setText("< Voltar");
        jButtonVoltar.setEnabled(false);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Próximo >");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.setEnabled(false);

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanelControleLayout = new javax.swing.GroupLayout(jPanelControle);
        jPanelControle.setLayout(jPanelControleLayout);
        jPanelControleLayout.setHorizontalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanelControleLayout.setVerticalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPassos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(jPanelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPassos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldP1NomeEscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldP1NomeEscKeyReleased
        // TODO add your handling code here:
        if (this.jTextFieldP1NomeEsc.getText().equals("")) {
            this.jLabelP1Informacao.setText("Forneça um nome de classe Java válido");
            this.jTextFieldLocalArq.setText("");
            this.jButtonProximo.setEnabled(false);
        } else if (ValidaValores.validaNomeClasse(this.jTextFieldP1NomeEsc.getText())) {
            this.jLabelP1Informacao.setText("");
            this.jTextFieldLocalArq.setText(this.caminho + this.jTextFieldP1NomeEsc.getText() + ".java");
            this.jButtonProximo.setEnabled(true);
        } else {
            this.jLabelP1Informacao.setText("O nome da classe não é válido");
            this.jButtonProximo.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldP1NomeEscKeyReleased

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        switch (this.passoAtual) {
            case 1:
                this.jScrollPanePrincipal.setViewportView(this.jPanelPasso2);
                this.jButtonVoltar.setEnabled(true);
                this.jLabelPasso1.setEnabled(false);
                this.jLabelPasso2.setEnabled(true);
                this.passoAtual = 2;
            break;
            case 2:
                this.jScrollPanePrincipal.setViewportView(this.jPanelPasso3);
                this.jLabelPasso2.setEnabled(false);
                this.jLabelPasso3.setEnabled(true);
                this.passoAtual = 3;
            break;
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        switch (this.passoAtual) {
            case 2:
                this.jScrollPanePrincipal.setViewportView(this.jPanelPasso1);
                this.jButtonVoltar.setEnabled(false);
                this.jButtonProximo.setEnabled(true);
                this.jLabelPasso1.setEnabled(true);
                this.jLabelPasso2.setEnabled(false);
                this.passoAtual = 1;
            break;
            case 3:
                this.jScrollPanePrincipal.setViewportView(this.jPanelPasso2);
                this.jButtonProximo.setEnabled(true);
                this.jLabelPasso2.setEnabled(true);
                this.jLabelPasso3.setEnabled(false);
                this.passoAtual = 2;
            break;
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jRadioButtonCentralizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCentralizadaActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonCentralizada.isSelected()) {
            this.jRadioButtonDistribuida.setSelected(false);
            this.jRadioButtonCentralizada.setSelected(true);
        } else {
            this.jRadioButtonDistribuida.setSelected(true);
            this.jRadioButtonCentralizada.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonCentralizadaActionPerformed

    private void jRadioButtonDistribuidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDistribuidaActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonDistribuida.isSelected()) {
            this.jRadioButtonDistribuida.setSelected(true);
            this.jRadioButtonCentralizada.setSelected(false);
        } else {
            this.jRadioButtonDistribuida.setSelected(false);
            this.jRadioButtonCentralizada.setSelected(true);
        }
    }//GEN-LAST:event_jRadioButtonDistribuidaActionPerformed

    private void jRadioButtonEstaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstaticaActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonEstatica.isSelected()) {
            this.jRadioButtonDinamica.setSelected(false);
            this.jRadioButtonEstatica.setSelected(true);
            setEnableDinamica(false);
        } else {
            this.jRadioButtonDinamica.setSelected(true);
            this.jRadioButtonEstatica.setSelected(false);
            setEnableDinamica(true);
        }
    }//GEN-LAST:event_jRadioButtonEstaticaActionPerformed

    private void jRadioButtonDinamicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDinamicaActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButtonDinamica.isSelected()) {
            this.jRadioButtonDinamica.setSelected(true);
            this.jRadioButtonEstatica.setSelected(false);
            setEnableDinamica(true);
        } else {
            this.jRadioButtonDinamica.setSelected(false);
            this.jRadioButtonEstatica.setSelected(true);
            setEnableDinamica(false);
        }
    }//GEN-LAST:event_jRadioButtonDinamicaActionPerformed

    private void jRadioButtonP2TempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP2TempoActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP2Tempo.setSelected(true);
        this.jRadioButtonP2Tarefa.setSelected(false);
        this.jRadioButtonP2Misto.setSelected(false);
    }//GEN-LAST:event_jRadioButtonP2TempoActionPerformed

    private void jRadioButtonP2TarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP2TarefaActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP2Tempo.setSelected(false);
        this.jRadioButtonP2Tarefa.setSelected(true);
        this.jRadioButtonP2Misto.setSelected(false);
    }//GEN-LAST:event_jRadioButtonP2TarefaActionPerformed

    private void jRadioButtonP2MistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP2MistoActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP2Tempo.setSelected(false);
        this.jRadioButtonP2Tarefa.setSelected(false);
        this.jRadioButtonP2Misto.setSelected(true);
    }//GEN-LAST:event_jRadioButtonP2MistoActionPerformed

    private void jRadioButtonP3RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP3RandomActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP3Random.setSelected(true);
        this.jRadioButtonP3Crescente.setSelected(false);
        this.jRadioButtonP3Decrescente.setSelected(false);
        this.ordenacao = "Random";
        inserirFormula(null);
    }//GEN-LAST:event_jRadioButtonP3RandomActionPerformed

    private void jRadioButtonP3DecrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP3DecrescenteActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP3Random.setSelected(false);
        this.jRadioButtonP3Crescente.setSelected(false);
        this.jRadioButtonP3Decrescente.setSelected(true);
        this.ordenacao = "Decrescente";
        inserirFormula(null);
    }//GEN-LAST:event_jRadioButtonP3DecrescenteActionPerformed

    private void jRadioButtonP3CrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonP3CrescenteActionPerformed
        // TODO add your handling code here:
        this.jRadioButtonP3Random.setSelected(false);
        this.jRadioButtonP3Crescente.setSelected(true);
        this.jRadioButtonP3Decrescente.setSelected(false);
        this.ordenacao = "Crescente";
        inserirFormula(null);
    }//GEN-LAST:event_jRadioButtonP3CrescenteActionPerformed

    private void jButtonP3TComputacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3TComputacaoActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [TCP]");
    }//GEN-LAST:event_jButtonP3TComputacaoActionPerformed

    private void jButtonP3AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3AddActionPerformed
        // TODO add your handling code here:
        inserirFormula(" +");
    }//GEN-LAST:event_jButtonP3AddActionPerformed

    private void jButtonP3VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3VoltarActionPerformed
        // TODO add your handling code here:
        String temp[] = this.formula.split(" ");
        this.formula = "";
        if(temp!=null){
            this.formula += temp[0];
        }
        for(int i=1; i < temp.length-1; i++){
            this.formula += " " + temp[i];
        }
        inserirFormula(null);
    }//GEN-LAST:event_jButtonP3VoltarActionPerformed

    private void jButtonP3NTSubmetidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3NTSubmetidasActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [NTS]");
    }//GEN-LAST:event_jButtonP3NTSubmetidasActionPerformed

    private void jButtonP3NTConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3NTConcluidasActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [NTC]");
    }//GEN-LAST:event_jButtonP3NTConcluidasActionPerformed

    private void jButtonP3NTAtendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3NTAtendidasActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [NTA]");
    }//GEN-LAST:event_jButtonP3NTAtendidasActionPerformed

    private void jButtonP3TComunicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3TComunicacaoActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [TC]");
    }//GEN-LAST:event_jButtonP3TComunicacaoActionPerformed

    private void jButtonP3PComputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP3PComputUserActionPerformed
        // TODO add your handling code here:
        inserirFormula(" [PCU]");
    }//GEN-LAST:event_jButtonP3PComputUserActionPerformed

    private void jTextFieldP3FormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP3FormulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP3FormulaActionPerformed

    private void setEnableDinamica(boolean b) {
        jLabelP2Forma.setEnabled(b);
        jRadioButtonP2Tempo.setEnabled(b);
        jRadioButtonP2Tarefa.setEnabled(b);
        jRadioButtonP2Misto.setEnabled(b);
        jFormattedTextFieldP2Tempo.setEnabled(b);
        jFormattedTextFieldP2Misto.setEnabled(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GerarEscalonador dialog = new GerarEscalonador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonP3AbreParent;
    private javax.swing.JButton jButtonP3Add;
    private javax.swing.JButton jButtonP3Div;
    private javax.swing.JButton jButtonP3FechaParent;
    private javax.swing.JButton jButtonP3Mult;
    private javax.swing.JButton jButtonP3NTAtendidas;
    private javax.swing.JButton jButtonP3NTConcluidas;
    private javax.swing.JButton jButtonP3NTSubmetidas;
    private javax.swing.JButton jButtonP3PComputUser;
    private javax.swing.JButton jButtonP3Sub;
    private javax.swing.JButton jButtonP3TComputacao;
    private javax.swing.JButton jButtonP3TComunicacao;
    private javax.swing.JButton jButtonP3Voltar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JFormattedTextField jFormattedTextFieldP2Misto;
    private javax.swing.JFormattedTextField jFormattedTextFieldP2Tempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFormula;
    private javax.swing.JLabel jLabelLocalArq;
    private javax.swing.JLabel jLabelNomeEsc;
    private javax.swing.JLabel jLabelP1Informacao;
    private javax.swing.JLabel jLabelP1Informacao1;
    private javax.swing.JLabel jLabelP1Informacao2;
    private javax.swing.JLabel jLabelP2Forma;
    private javax.swing.JLabel jLabelPasso1;
    private javax.swing.JLabel jLabelPasso2;
    private javax.swing.JLabel jLabelPasso3;
    private javax.swing.JLabel jLabelPassos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelControle;
    private javax.swing.JPanel jPanelPasso1;
    private javax.swing.JPanel jPanelPasso2;
    private javax.swing.JPanel jPanelPasso3;
    private javax.swing.JPanel jPanelPassos;
    private javax.swing.JRadioButton jRadioButtonCentralizada;
    private javax.swing.JRadioButton jRadioButtonDinamica;
    private javax.swing.JRadioButton jRadioButtonDistribuida;
    private javax.swing.JRadioButton jRadioButtonEstatica;
    private javax.swing.JRadioButton jRadioButtonP2Misto;
    private javax.swing.JRadioButton jRadioButtonP2Tarefa;
    private javax.swing.JRadioButton jRadioButtonP2Tempo;
    private javax.swing.JRadioButton jRadioButtonP3Crescente;
    private javax.swing.JRadioButton jRadioButtonP3Decrescente;
    private javax.swing.JRadioButton jRadioButtonP3Random;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldLocalArq;
    private javax.swing.JTextField jTextFieldP1NomeEsc;
    private javax.swing.JTextField jTextFieldP3Formula;
    // End of variables declaration//GEN-END:variables

    private void inserirFormula(String token) {
        if(token != null){
            this.formula += token;
        }
        this.jTextFieldP3Formula.setText(this.ordenacao+"("+this.formula+" )");
    }
}
